# 实验数据及配置
std: [1, 1, 1, 1, 1, 1]  # VLP各LED的标准值

VLPfile: '20251127/20251127_173203_57.txt'
TSfile: '20251127/WU1127.txt'
IMUfile: '20251127/MT_07782A2B_012-001.txt' # 创建时间 17:32:08
idx1: 1363 # 全站仪起始点号
idx2: 1468 # 全站仪终止点号
t0_TS: 17.8 # 全站仪起始时间戳
t0_IMU: 5.7 # IMU起始时间戳